### ISSUE TITLE
🐞 plugins.javalent.com appears to be down

### ISSUE THREAD

**Issue by miscoined** [javalent/Javalents-Plugins#9]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

plugins.javalent.com should be accessible for documentation

### Current behaviour

plugins.javalent.com doesn't load

### Reproduction

Go to https://plugins.javalent.com

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

N/A

### Plugin Version

N/A

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by sigrunixia** [comment]
This has been resolved. Thank you!
